Repository Gr770/CK3-Community-Title-Project, pull requests merged in 2020-10, with the labels that each got.

#59 Master Fixes
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Fixes

#67 Culture Names
  localization/english/culture/cultures_l_english.yml
  localization/french/culture/cultures_l_french.yml
  localization/german/culture/cultures_l_german.yml
  localization/spanish/culture/cultures_l_spanish.yml
Labels: Update

#71 Master Fixes
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/culture/cultures_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Fixes

#73 Font - Ready
  fonts/ctp_fonts/CharisSIL-B.ttf
  fonts/ctp_fonts/CharisSIL-BI.ttf
  fonts/ctp_fonts/CharisSIL-I.ttf
  fonts/ctp_fonts/CharisSIL-R.ttf
  fonts/fonts.font
Labels: Addition, New feature fork

#72 Master Fixes
  Dummy.txt
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Fixes

#87 Council Compatibility Update - Ready
  common/council_positions/00_council_positions.txt
  common/customizable_localization/00_ctp_councillor_custom_loc.txt
  localization/english/council_l_english.yml
  localization/french/council_l_french.yml
  localization/german/council_l_german.yml
  localization/spanish/council_l_spanish.yml
Labels: Compatibility, Fixes

#63 Better Vlach (Old Romanian) titles
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/culture/cultures_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/french/culture/cultures_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/german/culture/cultures_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
  localization/spanish/culture/cultures_l_spanish.yml
Labels: Fixes

#35 Knights - Ready
  common/customizable_localization/00_knight_culture.txt
  localization/english/knight_culture_l_english.yml
  localization/french/knight_culture_l_french.yml
  localization/german/knight_culture_l_german.yml
  localization/spanish/knight_culture_l_spanish.yml
Labels: New feature fork

#83 East Slavic localizations
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/ctp_council_custom_loc_l_german.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Addition, Fixes

#84 Old High German
  common/customizable_localization/00_ctp_councillor_custom_loc.txt
  common/flavorization/00_CTP.txt
  localization/english/ctp_council_custom_loc_l_english.yml
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/ctp_council_custom_loc_l_french.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/ctp_council_custom_loc_l_german.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/ctp_council_custom_loc_l_spanish.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Fixes

#88 We should fix what we do have №2
  common/customizable_localization/00_knight_culture.txt
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/culture/cultures_l_english.yml
  localization/english/knight_culture_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/french/culture/cultures_l_french.yml
  localization/french/knight_culture_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/german/culture/cultures_l_german.yml
  localization/german/knight_culture_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
  localization/spanish/culture/cultures_l_spanish.yml
  localization/spanish/knight_culture_l_spanish.yml
Labels: Compatibility, Fixes

#77 Master Fixes
  Dummy.txt
  README.md
  common/council_positions/00_council_positions.txt
  common/customizable_localization/00_ctp_councillor_custom_loc.txt
  common/flavorization/00_CTP.txt
  localization/english/council_l_english.yml
  localization/english/ctp_council_custom_loc_l_english.yml
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/knight_culture_l_english.yml
  localization/french/council_l_french.yml
  localization/french/ctp_council_custom_loc_l_french.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/french/knight_culture_l_french.yml
  localization/german/council_l_german.yml
  localization/german/ctp_council_custom_loc_l_german.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/german/culture/cultures_l_german.yml
  localization/german/knight_culture_l_german.yml
  localization/spanish/council_l_spanish.yml
  localization/spanish/ctp_council_custom_loc_l_spanish.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
  localization/spanish/knight_culture_l_spanish.yml
Labels: Fixes

#91 Fixes
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/culture/cultures_l_english.yml
  localization/english/knight_culture_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/french/culture/cultures_l_french.yml
  localization/french/knight_culture_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/german/knight_culture_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
  localization/spanish/knight_culture_l_spanish.yml
Labels: Fixes

#92 Earl/Earldom
  common/customizable_localization/00_ctp_conditional.txt
  localization/english/culture/ctp_titles_l_english.yml
Labels: New feature fork

#94 Master Fixes
  common/flavorization/00_CTP_backup.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Fixes

#97 Independent Duchy and County Ready
  common/customizable_localization/00_ctp_independent_county.txt
  common/customizable_localization/00_ctp_independent_duchy.txt
  common/customizable_localization/00_knight_culture.txt
  common/flavorization/00_ctp_titles_01.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Fixes, New feature fork

#98 Marches and Platinates Ready!
  common/customizable_localization/00_ctp_duchy.txt
  common/flavorization/00_ctp_titles_01.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: New feature fork

#105 Friday Hot Fix
  common/customizable_localization/00_ctp_county.txt
  common/customizable_localization/00_ctp_duchy.txt
  common/customizable_localization/00_ctp_independent_county.txt
  common/customizable_localization/00_ctp_independent_duchy.txt
  common/flavorization/00_ctp_titles_01.txt
  fonts/Fondamento/Fondamento-Italic.ttf
  fonts/Fondamento/Fondamento-Regular.ttf
  fonts/Fondamento/OFL.txt
  fonts/Gitan/GitanLatin-Bold-Italic.otf
  fonts/Gitan/GitanLatin-Bold.otf
  fonts/Gitan/GitanLatin-Italic.otf
  fonts/Gitan/GitanLatin-Regular.otf
  fonts/Gitan/Rosetta EULA 4.0 - Paradox.pdf
  fonts/mapfont/Paradox_King_Script.otf
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Fixes

#106 Clean Up
  common/flavorization/00_ctp_titles_01.txt
  dummy.txt
Labels: Overhaul

#118 Cultures
  localization/english/culture/cultures_l_english.yml
Labels: Update

#123 Cultures
  localization/english/culture/cultures_l_english.yml
  localization/french/culture/cultures_l_french.yml
  localization/german/culture/cultures_l_german.yml
  localization/spanish/culture/cultures_l_spanish.yml
Labels: Update

#122 Clean up title file1
  common/customizable_localization/00_ctp_independent_county.txt
  common/customizable_localization/00_ctp_independent_duchy.txt
  common/flavorization/00_ctp_titles_01.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Overhaul

#127 East African
  common/customizable_localization/00_ctp_councillor_custom_loc.txt
  common/customizable_localization/00_ctp_duchy.txt
  common/customizable_localization/00_ctp_independent_duchy.txt
  common/flavorization/00_ctp_titles_02.txt
  localization/english/ctp_council_custom_loc_l_english.yml
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/ctp_council_custom_loc_l_french.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/ctp_council_custom_loc_l_german.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/ctp_council_custom_loc_l_spanish.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Addition

#121 Playtest 1.1
  common/customizable_localization/00_ctp_barony.txt
  common/customizable_localization/00_ctp_councillor_custom_loc.txt
  common/customizable_localization/00_ctp_duchy.txt
  common/customizable_localization/00_ctp_independent_county.txt
  common/customizable_localization/00_ctp_independent_duchy.txt
  common/flavorization/00_ctp_titles_01.txt
  common/flavorization/00_ctp_titles_02.txt
  dummy.txt
  fonts/Fondamento/Fondamento-Italic.ttf
  fonts/Fondamento/Fondamento-Regular.ttf
  fonts/Gitan/GitanLatin-Bold-Italic.otf
  fonts/Gitan/GitanLatin-Bold.otf
  fonts/Gitan/GitanLatin-Italic.otf
  fonts/Gitan/GitanLatin-Regular.otf
  fonts/mapfont/ParadoxKingScript-RegularIFP(1).otf
  localization/english/ctp_council_custom_loc_l_english.yml
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/culture/cultures_l_english.yml
  localization/french/ctp_council_custom_loc_l_french.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/french/culture/cultures_l_french.yml
  localization/german/ctp_council_custom_loc_l_german.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/german/culture/cultures_l_german.yml
  localization/spanish/ctp_council_custom_loc_l_spanish.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
  localization/spanish/culture/cultures_l_spanish.yml
Labels: Pre-Merge
