Repository Gr770/CK3-Community-Title-Project, pull requests merged in 2020-09, with the labels that each got.

#20 Italian
  common/flavorization/00_title_holders.txt
  localization/english/culture/culture_titles_l_english.yml
  localization/french/culture/culture_titles_l_french.yml
  localization/german/culture/culture_titles_l_german.yml
  localization/spanish/culture/culture_titles_l_spanish.yml
Labels: enhancement

#22 Central German (Cleaner)
  common/flavorization/00_title_holders.txt
  localization/english/culture/cultures_l_english.yml
  localization/french/culture/cultures_l_french.yml
  localization/german/culture/cultures_l_german.yml
  localization/spanish/culture/cultures_l_spanish.yml
Labels: enhancement

#26 Updated title_holders to only include modded titles
  common/flavorization/00_CTP.txt
  common/flavorization/00_flavorization.txt
  common/flavorization/00_title_holders.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/culture/culture_titles_l_english.yml
  localization/english/culture/cultures_l_english.yml
  localization/french/culture/culture_titles_l_french.yml
  localization/french/culture/cultures_l_french.yml
  localization/german/culture/culture_titles_l_german.yml
  localization/german/culture/cultures_l_german.yml
  localization/spanish/culture/cultures_l_spanish.yml
Labels: enhancement

#21 Arabic Flavourisation
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
Labels: feature

#31 Update cultures_l_english.yml
  localization/english/culture/cultures_l_english.yml
Labels: Fixes

#30 Update ctp_titles_l_english.yml
  localization/english/culture/ctp_titles_l_english.yml
Labels: Fixes

#39 Master Fix Request
  README.md
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
Labels: Fixes

#28 Russian Culture
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_I_french.yml
  localization/german/culture/ctp_titles_I_german.yml
  localization/spanish/culture/ctp_titles_I_spainish.yml
Labels: Addition

#45 Master Fixes
  Dummy
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
Labels: Fixes

#47 Master Fix Request
  Dummy
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/culture/cultures_l_english.yml
  localization/french/culture/ctp_titles_I_french.yml
  localization/french/culture/ctp_titles_l_french
  localization/french/culture/cultures_l_french.yml
  localization/german/culture/ctp_titles_I_german.yml
  localization/german/culture/ctp_titles_l_german
  localization/german/culture/cultures_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish
  localization/spanish/culture/ctp_titles_l_spanish.yml
  localization/spanish/culture/cultures_l_spanish.yml
Labels: Fixes

#53 Magyar Group - ready
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_I_french.yml
  localization/german/culture/ctp_titles_I_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Addition

#49 Master Fixes
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_I_french.yml
  localization/german/culture/ctp_titles_I_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Fixes

#54 Master Fixes
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
Labels: Fixes

#52 Latin Culture Group
  common/flavorization/00_CTP.txt
  localization/english/culture/ctp_titles_l_english.yml
Labels: Addition

#32 Russian localization
  localization/russian/bookmark/bookmark_hastings_1066_l_russian.yml
  localization/russian/bookmark/bookmark_iberia_1066_l_russian.yml
  localization/russian/bookmark/bookmark_northmen_867_l_russian.yml
  localization/russian/terrains_l_russian.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Addition

#60 Romans distinguish male & female chancellor
  common/customizable_localization/00_ctp_councillor_custom_loc.txt
Labels: Fixes
