Repository Gr770/CK3-Community-Title-Project, pull requests merged in 2020-12, with the labels that each got.

#156 Playtest
  common/customizable_localization/00_ctp_councillor.txt
  common/customizable_localization/00_ctp_kingdom.txt
  common/flavorization/00_ctp_arabic.txt
  common/flavorization/00_ctp_balto_finnic.txt
  common/flavorization/00_ctp_brythonic.txt
  common/flavorization/00_ctp_byzantine.txt
  common/flavorization/00_ctp_east_african.txt
  common/flavorization/00_ctp_east_slavic.txt
  common/flavorization/00_ctp_iberian.txt
  common/flavorization/00_ctp_latin.txt
  common/flavorization/00_ctp_magyar.txt
  common/flavorization/00_ctp_north_germanic.txt
  common/flavorization/00_ctp_south_slavic.txt
  common/flavorization/00_ctp_west_germanic.txt
  localization/english/character_l_english.yml
  localization/english/ctp_council_titles_l_english.yml
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/knight_culture_l_english.yml
  localization/french/character_l_french.yml
  localization/french/ctp_council_custom_loc_l_french.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/character_l_german.yml
  localization/german/ctp_council_custom_loc_l_german.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/character_l_spanish.yml
  localization/spanish/ctp_council_custom_loc_l_spanish.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Pre-Merge

#161 Western Slavic
  common/customizable_localization/00_ctp_county.txt
  common/customizable_localization/00_ctp_duchy.txt
  common/customizable_localization/00_ctp_family.txt
  common/customizable_localization/00_ctp_independent_duchy.txt
  common/customizable_localization/00_ctp_kingdom.txt
  common/flavorization/00_ctp_west_slavic.txt
  localization/english/culture/ctp_titles_l_english.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
Labels: Addition

#162 Updates
  common/customizable_localization/00_ctp_councillor.txt
  common/customizable_localization/00_ctp_county.txt
  common/customizable_localization/00_ctp_duchy.txt
  common/customizable_localization/00_ctp_family.txt
  common/customizable_localization/00_ctp_independent_county.txt
  common/customizable_localization/00_ctp_independent_duchy.txt
  common/customizable_localization/00_ctp_kingdom.txt
  common/customizable_localization/00_knight_culture.txt
  common/flavorization/00_ctp_arabic.txt
  common/flavorization/00_ctp_balto_finnic.txt
  common/flavorization/00_ctp_brythonic.txt
  common/flavorization/00_ctp_byzantine.txt
  common/flavorization/00_ctp_dravidian.txt
  common/flavorization/00_ctp_goidelic.txt
  common/flavorization/00_ctp_iberian.txt
  common/flavorization/00_ctp_magyar.txt
  common/flavorization/00_ctp_north_germanic.txt
  common/flavorization/00_ctp_west_germanic.txt
  localization/english/council_l_english.yml
  localization/english/ctp_council_titles_l_english.yml
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/culture/cultures_l_english.yml
  localization/english/knight_culture_l_english.yml
  localization/french/ctp_council_custom_loc_l_french.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/french/culture/cultures_l_french.yml
  localization/french/knight_culture_l_french.yml
  localization/german/ctp_council_custom_loc_l_german.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/german/culture/cultures_l_german.yml
  localization/german/knight_culture_l_german.yml
  localization/spanish/ctp_council_custom_loc_l_spanish.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
  localization/spanish/culture/cultures_l_spanish.yml
  localization/spanish/knight_culture_l_spanish.yml
Labels: Update

#160 India and Dravidian
  common/customizable_localization/00_ctp_councillor.txt
  common/customizable_localization/00_ctp_duchy.txt
  common/customizable_localization/00_ctp_family.txt
  common/customizable_localization/00_ctp_independent_county.txt
  common/customizable_localization/00_ctp_independent_duchy.txt
  common/customizable_localization/00_ctp_kingdom.txt
  common/customizable_localization/00_knight_culture.txt
  common/flavorization/00_ctp_dravidian.txt
  common/flavorization/00_ctp_indian.txt
  localization/english/character_l_english.yml
  localization/english/ctp_council_titles_l_english.yml
  localization/english/culture/ctp_titles_l_english.yml
  localization/english/knight_culture_l_english.yml
  localization/french/character_l_french.yml
  localization/french/ctp_council_custom_loc_l_french.yml
  localization/french/culture/ctp_titles_l_french.yml
  localization/french/knight_culture_l_french.yml
  localization/german/character_l_german.yml
  localization/german/ctp_council_custom_loc_l_german.yml
  localization/german/culture/ctp_titles_l_german.yml
  localization/german/knight_culture_l_german.yml
  localization/spanish/character_l_spanish.yml
  localization/spanish/ctp_council_custom_loc_l_spanish.yml
  localization/spanish/culture/ctp_titles_l_spanish.yml
  localization/spanish/knight_culture_l_spanish.yml
Labels: Addition
